title: Cramer Docs
description: Ryan Cramer's Personal Github
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true

markdown: kramdown

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
